### ISSUE TITLE
Wrong link for "ASPX to DotVVM converter" page 

### ISSUE THREAD

**Issue by PadreSVK** [riganti/dotvvm-samples-webforms-migration#1]
[Here](https://www.dotvvm.com/modernize) is wrong link to ASPX to DotVVM Converter page. Value of wrong link is [`https://www.dotvvm.com/webforms/converter`](https://www.dotvvm.com/webforms/converter) but it should be [`https://www.dotvvm.com/webforms/convert`](https://www.dotvvm.com/webforms/convert)

![image](https://user-images.githubusercontent.com/8254631/100386736-8ef14880-3026-11eb-8264-f0a2d9a2de19.png)

cc @tomasherceg, @Luko248

**Comment by Luko248** [comment]
Diky moc, zrovna dnes som to riešil :-) 

S pozdravom a prianím pekného dňa   |   Best regards

Lukáš Chylík
